version = 3
final_space = true

[palette]
  blue = '#1e66f5'
  closer = 'p:os'
  green = '#40a02b'
  lavender = '#7287FD'
  mauve = '#8839ef'
  os = '#ACB0BE'
  pink = '#ea76cb'
  red = '#d20f39'
  white = '#4c4f69'
  yellow = '#df8e1d'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .CurrentDate | date .Format }} '
    foreground = 'p:yellow'
    type = 'time'

  [[blocks.segments]]
    style = 'plain'
    template = '  {{ .Path }} '
    foreground = 'p:pink'
    type = 'path'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = 'p:red'
    type = 'ruby'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = 'p:green'
    type = 'node'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:mauve'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = ''
    foreground = 'p:closer'
    type = 'text'
